### PR TITLE
1.12 Items

### PR DESCRIPTION
**Pull request by SirChilledMrHobo**
Updated with 1.12 Items.

### CODE REVIEW

**Comment by SirChilledMrHobo** [comment]
I think you can edit the file, Andrew.

**Comment by andrewkm** [comment]
Can you please keep all lower case.

**Comment by SirChilledMrHobo** [comment]
Sure thing, switched to lower case and fixed lime from lime to L.

**Comment by SirChilledMrHobo** [comment]
Also removed splash potions, forgot because they were a different ID than drinkable potions.

**Pull request merged**
