### PR TITLE
Fully Update Item IDs for 1.13

### PR DESCRIPTION
**Pull request by LJKAzrael**
Updated all item IDs for the release of 1.13

### CODE REVIEW

**Comment by JamieSinn** [comment]
I'll take a look when I've got a chance

**Comment by LJKAzrael** [comment]
Ok and thank you. Enjoy your holidays.

Merry Christmas,
LJKAzrael

**Comment by JamieSinn** [comment]
You didn't edit the right file, you need to edit the items1.13.csv. Please move the changes to that file, and restore changes to the original file

**Comment by JamieSinn** [comment]
Nvm - I manually merged.

**Pull request closed without merging**
