### PR TITLE
SirChilledMrHobo's Potions and Enchanted books Removed.

### PR DESCRIPTION
**Pull request by SirChilledMrHobo**
Removed Potions and Enchanted books seeing how they can't be used in trade sings and would just throw people off.

### CODE REVIEW

**Comment by andrewkm** [comment]
Jamie let me know what you think of this, and if removing all these would somehow hurt ESS and it's setup.

**Comment by JamieSinn** [comment]
Currently that would destroy the cache of potions in trade signs as well as them with sell. I say no because this will do much more harm than good

**Comment by andrewkm** [comment]
Jamie can you please elaborate. Do we really have potions in signs and do we really allow sell hand on them?

**Comment by SirChilledMrHobo** [comment]
I just did /sell hand to some potions and server reports can't be sold to the server. I also tried to create a trade sign with a potion and it di not work. The tag "potion" used could not detect the potion in my inventory.

**Comment by JamieSinn** [comment]
the test is running /itemdb, as that'll either correctly identify the potion, or not.
If it identifies it, I do not want to remove them.

**Comment by SirChilledMrHobo** [comment]
Using /itemdb brings all potions as "potion #373" so it can not correctly identify potions by what type it is.

**Comment by andrewkm** [comment]
Jamie, I really don't think adding that adding this will cause any harm. Its literally all the same item number. @jamiesinn please go over what we use on our server in detail and  get back to us again. It would be nice to have this file cleaned up, and this accomplishes that.

**Comment by JamieSinn** [comment]
The only thing I can think of breaking is sg kits, but that shouldn't have any problems as it uses item numbers instead of names

**Comment by andrewkm** [comment]
So thoughts on merging it?

**Comment by JamieSinn** [comment]
I'd say go for it, and at worst rollback the file.

**Pull request merged**
